version: '3'

services:
  db:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: magento
      MARIADB_USER: magento
      MARIADB_PASSWORD: magento
    networks:
      - backend
  elastic:
    image: elasticsearch:8.5.3
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - "xpack.security.enabled=false"
      
    networks:
      - backend
  web:
    build:
      context: .
    container_name: magento2-container
    environment:
      DB_SERVER: mariadb
      ELASTICSEARCH_SERVER: elasticsearch
      MAGENTO_HOST: ${APP_URL}
      VIRTUAL_HOST: ${APP_URL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      USE_SSL: 1
      DEPLOY_SAMPLEDATA: 1
    ports:
      - 8080:80
    depends_on:
      - db
      - elastic
    networks:
      backend:
networks:
  backend:
